import test from 'node:test';
import assert from 'node:assert/strict';
import bcrypt from 'bcryptjs';
import type {AddressInfo} from 'node:net';
process.env.DATA_MODE='demo';process.env.NODE_ENV='test';process.env.JWT_SECRET='test-secret-only-012345678901234567890';process.env.ADMIN_EMAIL='admin@example.com';process.env.ADMIN_PASSWORD_HASH=await bcrypt.hash('test-password-only',10);
const {app}=await import('./app.js');
test('API demonstration, validation and administrative authorization',async()=>{const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}/api`;const request=(path:string,method='GET',body?:unknown,token?:string)=>fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});try{
const events=await (await request('/events')).json();assert.equal(events.length,6);assert.ok(events.every((e:any)=>e.is_demo));const filtered=await(await request('/events?city=Campinas')).json();assert.equal(filtered.length,1);assert.equal((await request('/events/unknown')).status,404);assert.equal((await request('/sports')).status,200);assert.equal((await request('/stories')).status,200);const profiles=await(await request('/stories')).json();assert.deepEqual(profiles.map((s:any)=>s.name),['Rebeca Andrade','Marta','Rafaela Silva','Tifanny Abreu']);assert.ok(profiles.every((s:any)=>!s.is_demo&&s.source_url.startsWith('https://')&&s.source_name));
assert.equal((await request('/participation','POST',{name:'A'})).status,400);const input={name:'Teste fictício',email:'demo@example.com',type:'Escola',city:'São Paulo',message:'Mensagem fictícia de demonstração.'};const created=await request('/participation','POST',input);assert.equal(created.status,201);assert.equal((await created.json()).simulated,true);assert.equal((await request('/admin/participation')).status,401);assert.equal((await request('/events','POST',events[0])).status,401);assert.equal((await request('/admin/login','POST',{email:'admin@example.com',password:'wrong'})).status,401);
const login=await request('/admin/login','POST',{email:'admin@example.com',password:'test-password-only'});assert.equal(login.status,200);const {token}=await login.json();assert.equal((await request('/stories','POST',{name:'Atleta teste',sport:'Judô',title:'História teste',description:'Descrição para validar fonte.',is_demo:false},token)).status,400);assert.equal((await request('/admin/participation','GET',undefined,token)).status,200);const event={name:'Evento de teste fictício',sport:'Judô',description:'Descrição do teste fictício.',date:'2027-01-01T12:00:00Z',location:'Local fictício',city:'São Paulo',state:'SP',category:'Escolar',is_demo:true};const response=await request('/events','POST',event,token);assert.equal(response.status,201);const record=await response.json();assert.equal((await request('/events/'+record.id,'PUT',{...event,name:'Evento atualizado'},token)).status,200);assert.equal((await request('/events/'+record.id,'DELETE',undefined,token)).status,204);assert.equal((await request('/events/'+record.id)).status,404);
}finally{await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));}});
